export const FETCH_DATA_FAVORITE_PRODUCTS_REQUEST =
  "FETCH_DATA_FAVORITE_PRODUCTS_REQUEST";
export const FETCH_DATA_FAVORITE_PRODUCTS_SUCCESS =
  "FETCH_DATA_FAVORITE_PRODUCTS_SUCCESS";
export const FETCH_DATA_FAVORITE_PRODUCTS_FAILURE =
  "FETCH_DATA_FAVORITE_PRODUCTS_FAILURE";
export const ADD_FAVORITE_PRODUCT = "ADD_FAVORITE_PRODUCT";
export const REMOVE_FAVORITE_PRODUCT = "REMOVE_FAVORITE_PRODUCT";

export const SET_IS_LOADING_BOX = "SET_IS_LOADING_BOX";

export const GET_VIEWED_PRODUCTS = "GET_VIEWED_PRODUCTS";
export const ADD_VIEWED_PRODUCT = "ADD_VIEWED_PRODUCTS";
export const REMOVE_VIEWED_PRODUCT = "REMOVE_VIEWED_PRODUCT";

export const SET_CART_VOUCHER = "SET_CART_VOUCHER";
export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const SET_CART_SUBTOTAL = "SET_CART_SUBTOTAL";
export const SET_CART_TOTAL = "SET_CART_TOTAL";
export const SET_CART_SHIPPING_COST = "SET_CART_SHIPPING_COST";

export const SET_CART_ADDRESS = "SET_CART_ADDRESS";
export const SET_CART_NOTE = "SET_CART_NOTE";
export const SET_CART_PAYMENT_METHOD = "SET_CART_PAYMENT_METHOD";
export const RESET_CART_PAYMENT = "RESET_CART_PAYMENT";

export const SET_CURRENT_ORDER_PAYMENT_PENDING =
  "SET_CURRENT_ORDER_PAYMENT_PENDING";
export const SET_CURRENT_ORDER_PAYMENT_PENDING_CREATE_DATE =
  "SET_CURRENT_ORDER_PAYMENT_PENDING_CREATE_DATE";
export const SET_CURRENT_ORDER_PAYMENT_PENDING_EXPIRED_DATE =
  "SET_CURRENT_ORDER_PAYMENT_PENDING_EXPIRED_DATE";

export const FETCH_DATA_NOTIFICATION_REQUEST =
  "FETCH_DATA_NOTIFICATION_REQUEST";
export const FETCH_DATA_NOTIFICATION_SUCCESS =
  "FETCH_DATA_NOTIFICATION_SUCCESS";
export const FETCH_DATA_NOTIFICATION_FAILURE =
  "FETCH_DATA_NOTIFICATION_FAILURE";
